"""Add monotonic seq column to chat_messages for stable ordering."""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "005"
down_revision: str | None = "004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _column_exists(table: str, column: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(col["name"] == column for col in inspector.get_columns(table))


def _index_exists(name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(idx["name"] == name for idx in inspector.get_indexes("chat_messages"))


def upgrade() -> None:
    if not _column_exists("chat_messages", "seq"):
        # Identity backfills existing rows in physical/heap order; true order for
        # previously tied created_at values is unrecoverable. New inserts are
        # strictly monotonic within each transaction flush order.
        op.execute(
            sa.text(
                "ALTER TABLE chat_messages "
                "ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"
            )
        )
    if not _index_exists("ix_chat_messages_session_id_seq"):
        op.create_index(
            "ix_chat_messages_session_id_seq",
            "chat_messages",
            ["session_id", "seq"],
            unique=False,
        )


def downgrade() -> None:
    if _index_exists("ix_chat_messages_session_id_seq"):
        op.drop_index("ix_chat_messages_session_id_seq", table_name="chat_messages")
    if _column_exists("chat_messages", "seq"):
        op.drop_column("chat_messages", "seq")
